cmake_minimum_required(VERSION 4.3)
project(strprogramavimas)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)

add_executable(strprogramavimas
        .idea/.gitignore
        .idea/editor.xml
        .idea/modules.xml
        .idea/strprogramavimas.iml
        .idea/vcs.xml
        .idea/workspace.xml
        .gitignore
        README.md
        main.cpp
)
